"""initial schema

Revision ID: 5a6b7a7995f1
Revises: 
Create Date: 2026-10-08 07:10:21.568546
"""
from alembic import op
import sqlalchemy as sa


revision = '5a6b7a7995f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('docker_image', sa.String(length=128), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('resource_weight', sa.Integer(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_category'), 'scenarios', ['category'], unique=False)
    op.create_index(op.f('ix_scenarios_slug'), 'scenarios', ['slug'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('scenario_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('setup_script', sa.Text(), nullable=False),
    sa.Column('verify_script', sa.Text(), nullable=False),
    sa.Column('score_config', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'version')
    )
    op.create_index(op.f('ix_scenario_versions_scenario_id'), 'scenario_versions', ['scenario_id'], unique=False)
    # scenarios <-> scenario_versions reference each other: this side is added once both tables exist
    op.create_foreign_key('fk_scenarios_current_version', 'scenarios', 'scenario_versions', ['current_version_id'], ['id'])
    op.create_table('training_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('scenario_version_id', sa.Integer(), nullable=True),
    sa.Column('scenario_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resource_weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=200), nullable=False),
    sa.Column('final_state', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_attempts_scenario_id'), 'training_attempts', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_training_attempts_status'), 'training_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_training_attempts_user_id'), 'training_attempts', ['user_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('cwd', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_attempt_id'), 'commands', ['attempt_id'], unique=False)
    op.create_table('lab_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('container_name', sa.String(length=64), nullable=False),
    sa.Column('container_id', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id'),
    sa.UniqueConstraint('container_name')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('maximum', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('verify_output', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_table('verification_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('check', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_attempt_id'), 'verification_results', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('fk_scenarios_current_version', 'scenarios', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_results_attempt_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_table('scores')
    op.drop_table('lab_containers')
    op.drop_index(op.f('ix_commands_attempt_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_training_attempts_user_id'), table_name='training_attempts')
    op.drop_index(op.f('ix_training_attempts_status'), table_name='training_attempts')
    op.drop_index(op.f('ix_training_attempts_scenario_id'), table_name='training_attempts')
    op.drop_table('training_attempts')
    op.drop_index(op.f('ix_scenario_versions_scenario_id'), table_name='scenario_versions')
    op.drop_table('scenario_versions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_scenarios_slug'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_category'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
